# Generated by Django 3.1.7 on 2021-03-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='is_main_img',
            field=models.BooleanField(default=False),
        ),
    ]
